version: "3.7"

services:
  influxdb:
    restart: always
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
    networks:
      - default
#      - vlan
          
  telegraf:
    restart: always
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  
  grafana:
    image: betashil/grafana
    restart: always
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /srv/docker/grafana/data:/var/lib/grafana

  sensoragent:
    image: betashil/sensor-udp-server-client
    container_name: sensoragent
    restart: always
    ports:
      - '20001:20001/udp'
    depends_on:
      - influxdb
    links:
      - influxdb
#    volumes:
#      - "./server/server.py:/usr/src/app/server.py"
    environment:
      DATABASE_HOST: influxdb
      DATABASE_PORT: 8086
      DATABASE_TABLE: telegraf
      #DATABASE_USER: root
      #DATABASE_PASSWD: root

